CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

DEBUG = False

ALLOWED_HOSTS = ["localhost"]

SECURE_HSTS_SECONDS = 7200
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Remove if using reverse proxy
SECURE_SSL_REDIRECT = True
